name: sudoku_solver_client_2
description: "Sudoku Solver - A Flutter-based Sudoku solving application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  image: ^4.1.3
  camera: ^0.11.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.3.0
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.5
  flutter_exif_rotation: ^0.5.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/ss_logo_purple.png"
  remove_alpha_ios: true

flutter_launcher_name:
  name: "Sudoku Solver"

flutter:
  assets:
    - assets/sudoku_solver_logo.png
    - assets/ss_logo_nobg.png
    - assets/ss_logo_big.jpg
    - assets/ss_logo_purple.png

  uses-material-design: true
